### ISSUE TITLE
1.0.3: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [pfalcon/sphinx_selective_exclude#11]
```
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/sphinx_selective_exclude-1.0.3
+ /usr/bin/python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing sphinx_selective_exclude.egg-info/PKG-INFO
writing dependency_links to sphinx_selective_exclude.egg-info/dependency_links.txt
writing namespace_packages to sphinx_selective_exclude.egg-info/namespace_packages.txt
writing top-level names to sphinx_selective_exclude.egg-info/top_level.txt
reading manifest file 'sphinx_selective_exclude.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'sphinx_selective_exclude.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 238, in run
    self.run_tests()
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 256, in run_tests
    test = unittest.main(
  File "/usr/lib64/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.8/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.8/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib64/python3.8/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.8/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.8/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib64/python3.8/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx_selective_exclude-1.0.3/sphinx_selective_exclude/eager_only.py", line 27, in <module>
    class EagerOnly(sphinx.directives.other.Only):
AttributeError: module 'sphinx' has no attribute 'directives'
```

**Comment by pfalcon** [comment]
There's a testsuite? I'm surprised.

The usual suspect would be changes on sphinx side (in new sphinx versions). I no longer use sphinx_selective_exclude for quite some time, so don't intend to look into this. Feel free to fork and maintain it going forward.

**Comment by kloczek** [comment]
So moment this module should be obsoleted and no longer used?
If yes you may advice python hypothesis maintainer (https://github.com/HypothesisWorks/hypothesis-python/) how to to get rid of use your module.

**Comment by pfalcon** [comment]
No, open-source software is a community software, where joy and burden of supporting it lies on the community itself. In other words, whoever uses it, deals with it. There's rarely a single party which can dictate what's obsolete and what's not, and what others should use.

**Comment by kloczek** [comment]
Sorry to say taht but your stantement has nothing to do with my question.
